SELECT B.MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE 
FROM REST_REVIEW A
LEFT JOIN MEMBER_PROFILE B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID IN (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID HAVING COUNT(*) = 3)
ORDER BY REVIEW_DATE, REVIEW_TEXT